# Generated by Django 3.0.8 on 2022-11-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poresult',
            name='polling_station',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
