# Generated by Django 3.0.8 on 2022-11-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0002_auto_20221124_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='assigned_polling_station',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='uchaguzi.PollingStation'),
        ),
    ]
