# Generated by Django 3.0.8 on 2022-11-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0002_auto_20221129_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poresult',
            name='polling_station',
            field=models.CharField(max_length=50),
        ),
    ]
