# Generated by Django 3.0.8 on 2022-11-30 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uchaguzi', '0003_auto_20221129_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='poresult',
            name='assigned_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
