# Generated by Django 3.0.8 on 2022-11-30 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uchaguzi', '0005_auto_20221130_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poresult',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
