# Generated by Django 3.0.8 on 2022-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0006_auto_20221130_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poresult',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
