# Generated by Django 3.0.8 on 2022-11-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0007_auto_20221130_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
