# Generated by Django 3.0.8 on 2022-12-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0009_auto_20221130_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='poresult',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
