# Generated by Django 3.0.8 on 2022-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0010_poresult_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingstation',
            name='is_published',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
