# Generated by Django 3.0.8 on 2022-12-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0011_pollingstation_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingstation',
            old_name='is_published',
            new_name='rejected_ballots',
        ),
    ]
