# Generated by Django 3.0.8 on 2022-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0013_pollingstation_registered_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingstation',
            name='registered_voters',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
