# Generated by Django 3.0.8 on 2022-12-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0014_auto_20221205_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
