# Generated by Django 3.0.8 on 2022-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0015_candidate_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
