# Generated by Django 3.0.8 on 2022-12-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0017_pollingstation_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
