# Generated by Django 3.0.8 on 2022-12-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0018_candidate_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.FileField(blank=True, default='https://res.cloudinary.com/ribiro/image/upload/v1639470342/lm8zifymtgmkowbzx53h.jpg', null=True, upload_to='uchaguzi-candidates'),
        ),
    ]
