# Generated by Django 3.0.8 on 2022-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0019_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.FileField(blank=True, default='https://res.cloudinary.com/ribiro/image/upload/v1670336131/uchaguzi-candidates/mini1_pkbi6l.png', null=True, upload_to='uchaguzi-candidates'),
        ),
    ]
