# Generated by Django 3.0.8 on 2022-12-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uchaguzi', '0020_auto_20221206_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.FileField(blank=True, default='https://res.cloudinary.com/ribiro/image/upload/v1670337280/uchaguzi-candidates/avatar_kr1kf2.png', null=True, upload_to='uchaguzi-candidates'),
        ),
    ]
